name: Steamed Design
favicon: null
layout_spectrum: 0.14855118934065104
typography_spectrum: 0.24868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0
  lightness: 0.7480492114555091
  saturation: 0.9018292466644198
  rhythmicContrast: 0.08771117264404893
purpose: []
